//Yui Lo


#include <stdio.h>


int main () {
 int ai;
 printf("\nel dato es de tipo entero, el formato de entrada es int.%i",ai);
 float af;
 printf("\nel dato es de tipo flotante, el formato de entrada es float.%f",af);
 double ad;
 printf("\nel dato de de tipo double, el formato de entrada es double.%lf",ad);

 printf("\nel dato es de tipo double, el formato de entrada es double.%e",ad);
 char ac;
 printf("\nel dato es de tipo carater, el formato de entrada es char.%c",ac);
 printf("\nel dato es de tipo carater, el formato de entrada es char.%i",ac);
char c[6]="cad";
printf("\nel dato de es de tipo cadena, el formato de entrada es cadena.%s",c);
char ca[6]="cad";
printf("\nel dato de es de tipo cadena, el formato de entrada es cadena.%s",ca);
getchar();



 return 0;}
