//Yui Lo

#include <stdio.h>
#include <stdlib.h>

int main(){
    printf( "El valor 92 usando el tipo de campo i es %i \n", 92);
    printf("El valor 92 usando el tipo de campo u es %u \n", 92);
    printf("El valor 92 usando el tipo de campo o es %o \n", 92);
    printf("El valor 92 usando el tipo de campo x es %x \n", 92);
    printf("El valor 92 usando el tipo de campo f es %f \n", 92.0);
    printf("El valor 92 usando el tipo de campo e es %e \n", 92.0);
    printf("El valor 92 usando el tipo de campo c es %c \n", '9');
    printf("El valor 92 usando el tipo de campo s es %s \n", "92");
    printf("Esta es %i , %c , %x" ,'b','b','b');

    return 0;


}
